collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/gallery"
    # REMOVE the media_folder and public_folder lines from here
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}