backend:
  name: github
  repo: aaronnsullivan/armadillo-tile
  branch: master
  base_url: https://armadillotile.com
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/gallery"
    media_folder: "../../images" # Tells CMS: Go up twice from src/gallery to find the images folder
    public_folder: "/images"      # Tells CMS: Write the path in the .md file as /images/photo.png
    create: true
    # ... rest of your fields
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["gallery"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}